### ISSUE TITLE
[BUG]: Camera turning white during some transitions

### ISSUE THREAD

**Issue by JaumeMontagut** [OverPowered-Team/TheWitcher#3]
**Bug description**
The camera sometimes turns white in certain transitions.

**Steps to reproduce**
1. Go to the "pillars" zone
2. Move until it performs the transition

**Expected behaviour**
The camera does the transition without any interruption.

**Actual behaviour**
The camera has a small flash in the middle of the transition.

**Game version**
Game release: v.0.2.3

**Screenshots**
![thing](https://user-images.githubusercontent.com/36292291/77580575-8d421480-6edc-11ea-85c6-e2d9ba057524.gif)

**Additional context**
Probably due to the LookAt function returning a value that makes the camera rotate in the opposite way, to the sky.
Can also be reproduced by inserting certain angles in the TriggerCamera script, such as (dist 20, hor angle 90, vert angle 45, transition time 2).

**Comment by christt105** [comment]
It's not "turning white". It's just you say in **Additional context**. The function to look at middle point between enemies has conflicts with some angles and looks to the opposite direction. We will take a look when we have a moment. Thank you!

**Comment by JaumeMontagut** [comment]
Maybe it's related to this issue on the camera [issue](https://github.com/OverPowered-Team/Alien-GameEngine/issues/121)
